=== woowacourse-teams/2024-code-zap/frontend/src/i18n/schema/Header.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Header i18n schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "myTemplates": { "type": "string" },
    "likedTemplates": { "type": "string" },
    "explore": { "type": "string" },
    "newTemplate": { "type": "string" },
    "login": { "type": "string" },
    "logout": { "type": "string" },
    "alertLogin": { "type": "string" },
    "newTemplateAria": { "type": "string" },
    "logoButton": { "type": "string" },
    "menu": { "type": "string" }
  },
  "required": [
    "myTemplates",
    "likedTemplates",
    "explore",
    "newTemplate",
    "login",
    "logout",
    "alertLogin",
    "newTemplateAria",
    "logoButton",
    "menu"
  ]
}

=== woowacourse-teams/2024-code-zap/frontend/src/i18n/en/Header.json
{
  "$schema": "../schema/Header.schema.json",

  "myTemplates": "My Templates",
  "likedTemplates": "Liked Templates",
  "explore": "Explore",
  "newTemplate": "New Template",
  "login": "Login",
  "logout": "Logout",
  "alertLogin": "Please log in.",
  "newTemplateAria": "Go to the page to create a new template.",
  "logoButton": "Logo button",
  "menu": "Menu"
}

=== woowacourse-teams/2024-code-zap/frontend/src/i18n/ko/Header.json
{
  "$schema": "../schema/Header.schema.json",

  "myTemplates": "내 템플릿",
  "likedTemplates": "좋아요한 템플릿",
  "explore": "구경가기",
  "newTemplate": "새 템플릿",
  "login": "로그인",
  "logout": "로그아웃",
  "alertLogin": "로그인을 해주세요.",
  "newTemplateAria": "템플릿 작성 페이지로 이동됩니다.",
  "logoButton": "로고 버튼",
  "menu": "메뉴"
}
